import type { SocialContentItem } from "@/lib/content/types";

export const COOKED: SocialContentItem[] = [
  {
    id: "cooked-exam-2am",
    slug: "exam-tomorrow-havent-studied",
    type: "cooked",
    category: "school",
    prompt: "My exam is tomorrow. I haven't studied. It's 2:47 AM.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Opening TikTok again would be an interesting strategic decision.",
    seo: { description: "Vote on whether an unprepared 2 AM exam situation is actually cooked." },
    featured: true,
  },
  {
    id: "cooked-liked-old-post",
    slug: "liked-crushs-post-from-2022",
    type: "cooked",
    category: "dating",
    prompt: "I accidentally liked my crush's post from 2022 while deep-scrolling.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Put the phone down.",
    seo: { description: "Vote on whether accidentally liking an old crush post is cooked." },
    featured: true,
  },
  {
    id: "cooked-rent-due-tomorrow",
    slug: "rent-due-tomorrow-broke",
    type: "cooked",
    category: "money",
    prompt: "Rent is due tomorrow. My account has $40 in it. Payday is in five days.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The landlord group chat energy is not it.",
    seo: { description: "Vote on whether being broke the day before rent is due is cooked." },
  },
  {
    id: "cooked-reply-all",
    slug: "hit-reply-all-by-accident",
    type: "cooked",
    category: "work",
    prompt: "I meant to vent about my manager to one coworker. I hit reply-all to the whole company.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Start drafting the resignation letter, just in case.",
    seo: { description: "Vote on whether an accidental reply-all vent is a career-ending cooked moment." },
    featured: true,
  },
  {
    id: "cooked-double-texted-group",
    slug: "double-booked-two-plans-tonight",
    type: "cooked",
    category: "social",
    prompt: "I told two different friend groups I'd hang out tonight. Both are expecting me in twenty minutes.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Somebody's getting the 'so sick' text.",
    seo: { description: "Vote on whether double-booking two plans in one night is cooked." },
  },
  {
    id: "cooked-left-on-read",
    slug: "left-on-read-after-great-first-date",
    type: "cooked",
    category: "dating",
    prompt: "The first date felt perfect. It's been three days and one blue checkmark with no reply.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Re-reading the last message for the ninth time won't change it.",
    seo: { description: "Vote on whether being left on read after a great first date is cooked." },
  },
  {
    id: "cooked-dog-barked-meeting",
    slug: "dog-barked-through-presentation",
    type: "cooked",
    category: "work",
    prompt: "Forgot to mute. My dog barked through the entire client presentation.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "At least someone in the meeting had strong opinions.",
    seo: { description: "Vote on whether an unmuted dog barking through a presentation is cooked." },
  },
  {
    id: "cooked-group-project-ghosted",
    slug: "group-project-partner-ghosted",
    type: "cooked",
    category: "school",
    prompt: "My group project partner has ghosted me for two weeks. The presentation is tomorrow morning.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Hope you like public speaking for two.",
    seo: { description: "Vote on whether a ghosted group project the night before presenting is cooked." },
  },
  {
    id: "cooked-four-free-trials",
    slug: "forgot-to-cancel-four-free-trials",
    type: "cooked",
    category: "money",
    prompt: "Signed up for four different free trials last month. Just remembered none of them got canceled.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The subscriptions won, as they always do.",
    seo: { description: "Vote on whether forgetting to cancel four free trials is a cooked financial moment." },
  },
  {
    id: "cooked-wrong-birthday-party",
    slug: "showed-up-to-wrong-birthday-party",
    type: "cooked",
    category: "social",
    prompt: "Walked into the party, hugged three strangers, and realized halfway through 'happy birthday' that this is the wrong apartment.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Free cake is free cake, technically.",
    seo: { description: "Vote on whether showing up to the wrong birthday party is cooked." },
  },
  {
    id: "cooked-stove-on",
    slug: "left-the-stove-on-already-at-work",
    type: "cooked",
    category: "random",
    prompt: "Pretty sure I left the stove on. I'm already twenty minutes into my commute.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Turning around now would make you extremely late for a maybe.",
    seo: { description: "Vote on whether possibly leaving the stove on is cooked." },
  },
  {
    id: "cooked-matched-exs-new-partner",
    slug: "matched-with-exs-new-partner",
    type: "cooked",
    category: "dating",
    prompt: "Opened the dating app and matched with my ex's new partner.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The algorithm has a sense of humor and it isn't kind.",
    seo: { description: "Vote on whether matching with your ex's new partner on a dating app is cooked." },
  },
  {
    id: "cooked-cc-boss-job-application",
    slug: "accidentally-cced-boss-job-application",
    type: "cooked",
    category: "work",
    prompt: "Sent a job application to a recruiter and accidentally CC'd my current boss.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The 'reply all' button strikes again.",
    seo: { description: "Vote on whether accidentally CCing your boss on a job application is cooked." },
    featured: true,
  },
  {
    id: "cooked-pop-quiz-skipped-classes",
    slug: "pop-quiz-after-skipping-classes",
    type: "cooked",
    category: "school",
    prompt: "Professor just announced a pop quiz. I've skipped the last three classes.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Vibes-based test-taking is a legitimate strategy, allegedly.",
    seo: { description: "Vote on whether a pop quiz after skipping class is cooked." },
  },
  {
    id: "cooked-mystery-subscription-charge",
    slug: "mystery-subscription-charge",
    type: "cooked",
    category: "money",
    prompt: "Checked the bank app. There's a recurring charge for something I genuinely do not recognize.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Somewhere out there, a company is very happy you haven't noticed.",
    seo: { description: "Vote on whether an unrecognized recurring bank charge is a cooked money moment." },
  },
  {
    id: "cooked-two-versions-same-story",
    slug: "told-two-versions-of-same-story",
    type: "cooked",
    category: "social",
    prompt: "Told two slightly different versions of the same story to the same friend group, on two different nights.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The fact-checkers have entered the group chat.",
    seo: { description: "Vote on whether telling two versions of the same story is cooked." },
  },
  {
    id: "cooked-locked-out-everyone-asleep",
    slug: "locked-out-everyone-asleep",
    type: "cooked",
    category: "random",
    prompt: "Locked out of the house. It's 1 AM and everyone inside is asleep with their phone on silent.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The porch furniture is about to become a bed.",
    seo: { description: "Vote on whether being locked out at 1 AM with everyone asleep is cooked." },
  },
  {
    id: "cooked-called-date-exs-name",
    slug: "called-date-by-exs-name",
    type: "cooked",
    category: "dating",
    prompt: "Called my date by my ex's name. Out loud. Twenty minutes into dinner.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The check, please — for both of us, separately, forever.",
    seo: { description: "Vote on whether calling your date by your ex's name is cooked." },
    featured: true,
  },
  {
    id: "cooked-love-you-manager",
    slug: "sent-love-you-to-manager",
    type: "cooked",
    category: "work",
    prompt: "Meant to text 'love you' to my partner. Sent it to my manager instead.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "New performance review category, unlocked.",
    seo: { description: "Vote on whether accidentally texting your manager 'love you' is cooked." },
  },
  {
    id: "cooked-essay-due-midnight",
    slug: "essay-due-midnight-no-intro",
    type: "cooked",
    category: "school",
    prompt: "The essay is due at midnight. It's 10:40 PM and the introduction still doesn't exist.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "ChatGPT tabs are opening themselves at this point.",
    seo: { description: "Vote on whether an essay due at midnight with no intro written is cooked." },
  },
];
