import type { SocialContentItem } from "@/lib/content/types";

export const COOKED: SocialContentItem[] = [
  {
    id: "cooked-exam-2am",
    slug: "exam-tomorrow-havent-studied",
    type: "cooked",
    category: "school",
    prompt: "My exam is tomorrow. I haven't studied. It's 2:47 AM.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Opening TikTok again would be an interesting strategic decision.",
    seo: { description: "Vote on whether an unprepared 2 AM exam situation is actually cooked." },
    featured: true,
  },
  {
    id: "cooked-liked-old-post",
    slug: "liked-crushs-post-from-2022",
    type: "cooked",
    category: "dating",
    prompt: "I accidentally liked my crush's post from 2022 while deep-scrolling.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Put the phone down.",
    seo: { description: "Vote on whether accidentally liking an old crush post is cooked." },
    featured: true,
  },
  {
    id: "cooked-rent-due-tomorrow",
    slug: "rent-due-tomorrow-broke",
    type: "cooked",
    category: "money",
    prompt: "Rent is due tomorrow. My account has $40 in it. Payday is in five days.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "The landlord group chat energy is not it.",
    seo: { description: "Vote on whether being broke the day before rent is due is cooked." },
  },
  {
    id: "cooked-reply-all",
    slug: "hit-reply-all-by-accident",
    type: "cooked",
    category: "work",
    prompt: "I meant to vent about my manager to one coworker. I hit reply-all to the whole company.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Start drafting the resignation letter, just in case.",
    seo: { description: "Vote on whether an accidental reply-all vent is a career-ending cooked moment." },
    featured: true,
  },
  {
    id: "cooked-double-texted-group",
    slug: "double-booked-two-plans-tonight",
    type: "cooked",
    category: "social",
    prompt: "I told two different friend groups I'd hang out tonight. Both are expecting me in twenty minutes.",
    optionA: { key: "cooked", label: "Cooked" },
    optionB: { key: "fine", label: "You're fine" },
    resultLine: "Somebody's getting the 'so sick' text.",
    seo: { description: "Vote on whether double-booking two plans in one night is cooked." },
  },
];
