import type { SocialContentItem } from "@/lib/content/types";

export const NORMAL: SocialContentItem[] = [
  {
    id: "normal-imaginary-arguments",
    slug: "imaginary-arguments-in-my-head",
    type: "normal",
    category: "thoughts",
    prompt: "I create entire imaginary arguments in my head that never actually happen.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Apparently we're all doing this.",
    seo: { description: "Vote on whether rehearsing imaginary arguments in your head is normal." },
    featured: true,
  },
  {
    id: "normal-reread-texts",
    slug: "reread-texts-before-sending",
    type: "normal",
    category: "habits",
    prompt: "I reread a text five times before sending it, even to close friends.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The group chat has no idea how much work went into that one 'lol'.",
    seo: { description: "Vote on whether rereading texts multiple times before sending is normal." },
  },
  {
    id: "normal-pretend-on-phone",
    slug: "pretend-to-be-on-phone-avoid-people",
    type: "normal",
    category: "social",
    prompt: "I pretend to be texting someone so I don't have to make eye contact with people I'm avoiding.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The phone has never once buzzed during these moments.",
    seo: { description: "Vote on whether faking a text to avoid eye contact is normal." },
    featured: true,
  },
  {
    id: "normal-check-read-receipts",
    slug: "check-read-receipts-obsessively",
    type: "normal",
    category: "relationships",
    prompt: "I check if my text was 'read' way more times than is probably healthy.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The read receipt was checked more than the actual reply, probably.",
    seo: { description: "Vote on whether obsessively checking read receipts is normal." },
  },
  {
    id: "normal-narrate-life",
    slug: "narrate-my-life-in-my-head",
    type: "normal",
    category: "thoughts",
    prompt: "I narrate my own life in my head like it's a documentary, especially while doing chores.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "'She reached for the dish soap, unaware of what was coming next.'",
    seo: { description: "Vote on whether narrating your own life like a documentary is normal." },
  },
  {
    id: "normal-same-tabs-month",
    slug: "same-three-tabs-open-for-a-month",
    type: "normal",
    category: "habits",
    prompt: "I've had the same three browser tabs open for over a month because I 'need them.'",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "They're basically permanent residents at this point.",
    seo: { description: "Vote on whether keeping the same browser tabs open for a month is normal." },
  },
  {
    id: "normal-on-my-way-lie",
    slug: "say-on-my-way-before-shoes-on",
    type: "normal",
    category: "habits",
    prompt: "I text 'I'm on my way' before I've actually put my shoes on.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Technically a future statement of intent, not a lie.",
    seo: { description: "Vote on whether texting 'on my way' before you've left is normal." },
    featured: true,
  },
  {
    id: "normal-same-day-package-win",
    slug: "same-day-package-feels-like-winning",
    type: "normal",
    category: "thoughts",
    prompt: "I feel a genuine sense of victory when a package arrives the same day it ships.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Small wins still count.",
    seo: { description: "Vote on whether feeling victorious about a same-day delivery is normal." },
  },
  {
    id: "normal-rehearse-how-are-you",
    slug: "rehearse-how-are-you-answer",
    type: "normal",
    category: "social",
    prompt: "I rehearse how I'll answer 'how are you?' before I've even reached the person.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "'Good, you?' takes more prep than it should.",
    seo: { description: "Vote on whether rehearsing small talk answers in advance is normal." },
  },
  {
    id: "normal-fall-asleep-during-movie",
    slug: "fall-asleep-during-anticipated-movie",
    type: "normal",
    category: "habits",
    prompt: "I've fallen asleep during a movie I was genuinely excited to watch — more than once.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The couch has other plans for your evening.",
    seo: { description: "Vote on whether falling asleep during a movie you wanted to watch is normal." },
  },
  {
    id: "normal-we-need-to-talk-anxiety",
    slug: "anxious-about-we-need-to-talk",
    type: "normal",
    category: "relationships",
    prompt: "I get a wave of anxiety when someone says 'we need to talk' — even when I know I didn't do anything.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Four words, infinite dread.",
    seo: { description: "Vote on whether feeling anxious over 'we need to talk' is normal." },
    featured: true,
  },
  {
    id: "normal-parking-spot-attachment",
    slug: "irrationally-attached-to-parking-spot",
    type: "normal",
    category: "habits",
    prompt: "I have a favorite parking spot and get irrationally annoyed when someone else takes it.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "It's not assigned. It just feels assigned.",
    seo: { description: "Vote on whether being attached to a specific parking spot is normal." },
  },
  {
    id: "normal-screenshot-conversations",
    slug: "screenshot-instead-of-remembering",
    type: "normal",
    category: "habits",
    prompt: "I screenshot conversations instead of trusting myself to remember what was actually said.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The camera roll is basically a legal archive at this point.",
    seo: { description: "Vote on whether screenshotting conversations for later is normal." },
  },
  {
    id: "normal-panic-clean-before-guests",
    slug: "panic-clean-already-clean-apartment",
    type: "normal",
    category: "habits",
    prompt: "I panic-clean my already-clean apartment right before someone comes over.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Clean isn't the same as 'ready for judgment.'",
    seo: { description: "Vote on whether panic-cleaning an already clean space before guests is normal." },
  },
  {
    id: "normal-middle-school-embarrassment",
    slug: "still-think-about-middle-school-cringe",
    type: "normal",
    category: "thoughts",
    prompt: "I still randomly think about an embarrassing thing I did in middle school.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "It's been over a decade. It still visits at 2 AM.",
    seo: { description: "Vote on whether still thinking about middle school embarrassment is normal." },
  },
];
