import type { SocialContentItem } from "@/lib/content/types";

export const NORMAL: SocialContentItem[] = [
  {
    id: "normal-imaginary-arguments",
    slug: "imaginary-arguments-in-my-head",
    type: "normal",
    category: "thoughts",
    prompt: "I create entire imaginary arguments in my head that never actually happen.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "Apparently we're all doing this.",
    seo: { description: "Vote on whether rehearsing imaginary arguments in your head is normal." },
    featured: true,
  },
  {
    id: "normal-reread-texts",
    slug: "reread-texts-before-sending",
    type: "normal",
    category: "habits",
    prompt: "I reread a text five times before sending it, even to close friends.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The group chat has no idea how much work went into that one 'lol'.",
    seo: { description: "Vote on whether rereading texts multiple times before sending is normal." },
  },
  {
    id: "normal-pretend-on-phone",
    slug: "pretend-to-be-on-phone-avoid-people",
    type: "normal",
    category: "social",
    prompt: "I pretend to be texting someone so I don't have to make eye contact with people I'm avoiding.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The phone has never once buzzed during these moments.",
    seo: { description: "Vote on whether faking a text to avoid eye contact is normal." },
    featured: true,
  },
  {
    id: "normal-check-read-receipts",
    slug: "check-read-receipts-obsessively",
    type: "normal",
    category: "relationships",
    prompt: "I check if my text was 'read' way more times than is probably healthy.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "The read receipt was checked more than the actual reply, probably.",
    seo: { description: "Vote on whether obsessively checking read receipts is normal." },
  },
  {
    id: "normal-narrate-life",
    slug: "narrate-my-life-in-my-head",
    type: "normal",
    category: "thoughts",
    prompt: "I narrate my own life in my head like it's a documentary, especially while doing chores.",
    optionA: { key: "yes", label: "Yes" },
    optionB: { key: "not_me", label: "Not me" },
    resultLine: "'She reached for the dish soap, unaware of what was coming next.'",
    seo: { description: "Vote on whether narrating your own life like a documentary is normal." },
  },
];
