import type { SocialContentItem } from "@/lib/content/types";

export const QUICK_FIRE: SocialContentItem[] = [
  {
    id: "qf-call-text",
    slug: "call-or-text",
    type: "quick_fire",
    category: "communication",
    prompt: "",
    optionA: { key: "a", label: "Call" },
    optionB: { key: "b", label: "Text" },
  },
  {
    id: "qf-stay-in-go-out",
    slug: "stay-in-or-go-out",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Stay in" },
    optionB: { key: "b", label: "Go out" },
  },
  {
    id: "qf-save-spend",
    slug: "save-or-spend",
    type: "quick_fire",
    category: "money",
    prompt: "",
    optionA: { key: "a", label: "Save" },
    optionB: { key: "b", label: "Spend" },
  },
  {
    id: "qf-ghost-explain",
    slug: "ghost-or-explain",
    type: "quick_fire",
    category: "relationships",
    prompt: "",
    optionA: { key: "a", label: "Ghost" },
    optionB: { key: "b", label: "Explain" },
  },
  {
    id: "qf-iphone-android",
    slug: "iphone-or-android",
    type: "quick_fire",
    category: "tech",
    prompt: "",
    optionA: { key: "a", label: "iPhone" },
    optionB: { key: "b", label: "Android" },
  },
  {
    id: "qf-love-money",
    slug: "love-or-money",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Love" },
    optionB: { key: "b", label: "Money" },
  },
  {
    id: "qf-morning-night",
    slug: "morning-or-night",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Morning person" },
    optionB: { key: "b", label: "Night owl" },
  },
  {
    id: "qf-career-relationship",
    slug: "career-or-relationship",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Career" },
    optionB: { key: "b", label: "Relationship" },
  },
  {
    id: "qf-beach-mountains",
    slug: "beach-or-mountains",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Beach" },
    optionB: { key: "b", label: "Mountains" },
  },
  {
    id: "qf-sweet-salty",
    slug: "sweet-or-salty",
    type: "quick_fire",
    category: "food",
    prompt: "",
    optionA: { key: "a", label: "Sweet" },
    optionB: { key: "b", label: "Salty" },
  },
  {
    id: "qf-coffee-tea",
    slug: "coffee-or-tea",
    type: "quick_fire",
    category: "food",
    prompt: "",
    optionA: { key: "a", label: "Coffee" },
    optionB: { key: "b", label: "Tea" },
  },
  {
    id: "qf-introvert-extrovert",
    slug: "introvert-or-extrovert",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Introvert" },
    optionB: { key: "b", label: "Extrovert" },
  },
  {
    id: "qf-plan-wing-it",
    slug: "plan-or-wing-it",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Plan it out" },
    optionB: { key: "b", label: "Wing it" },
  },
  {
    id: "qf-early-late",
    slug: "early-or-late",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Always early" },
    optionB: { key: "b", label: "Always late" },
  },
  {
    id: "qf-city-suburbs",
    slug: "city-or-suburbs",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "City" },
    optionB: { key: "b", label: "Suburbs" },
  },
  {
    id: "qf-books-movies",
    slug: "books-or-movies",
    type: "quick_fire",
    category: "entertainment",
    prompt: "",
    optionA: { key: "a", label: "Books" },
    optionB: { key: "b", label: "Movies" },
  },
  {
    id: "qf-summer-winter",
    slug: "summer-or-winter",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Summer" },
    optionB: { key: "b", label: "Winter" },
  },
  {
    id: "qf-cash-card",
    slug: "cash-or-card",
    type: "quick_fire",
    category: "money",
    prompt: "",
    optionA: { key: "a", label: "Cash" },
    optionB: { key: "b", label: "Card" },
  },
  {
    id: "qf-window-aisle",
    slug: "window-or-aisle-seat",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Window seat" },
    optionB: { key: "b", label: "Aisle seat" },
  },
  {
    id: "qf-dogs-cats",
    slug: "dogs-or-cats",
    type: "quick_fire",
    category: "lifestyle",
    prompt: "",
    optionA: { key: "a", label: "Dogs" },
    optionB: { key: "b", label: "Cats" },
  },
];
