import type { SocialContentItem } from "@/lib/content/types";

export const WHOS_WRONG: SocialContentItem[] = [
  {
    id: "wrong-roommate-boyfriend-rent",
    slug: "roommates-boyfriend-stays-over",
    type: "whos_wrong",
    category: "roommates",
    prompt:
      "My roommate's boyfriend stays over five nights a week. I asked him to start contributing toward rent.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Roommate" },
    seo: { description: "Vote on who's wrong: asking a roommate's live-in boyfriend to pay rent." },
    featured: true,
  },
  {
    id: "wrong-wifi-password",
    slug: "changed-wifi-password-over-food",
    type: "whos_wrong",
    category: "roommates",
    prompt: "My roommate keeps eating my food, so I changed the Wi-Fi password until they stop.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Roommate" },
    seo: { description: "Vote on who's wrong: changing the Wi-Fi password to stop a roommate eating your food." },
    featured: true,
  },
  {
    id: "wrong-split-bill-drinks",
    slug: "split-bill-evenly-i-didnt-drink",
    type: "whos_wrong",
    category: "friends",
    prompt:
      "My friends want to split the bill evenly, but I didn't drink and ordered the cheapest thing on the menu.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Friends" },
    seo: { description: "Vote on who's wrong: splitting a bill evenly when one person barely ordered anything." },
  },
  {
    id: "wrong-family-group-chat",
    slug: "muted-family-group-chat",
    type: "whos_wrong",
    category: "family",
    prompt:
      "I muted the family group chat because of the constant forwarded messages. My mom found out and is hurt.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Mom" },
    seo: { description: "Vote on who's wrong: muting a family group chat full of forwards." },
  },
  {
    id: "wrong-coworker-credit",
    slug: "coworker-presented-my-idea",
    type: "whos_wrong",
    category: "work",
    prompt:
      "I mentioned an idea to a coworker over coffee. They presented it as their own in the team meeting the next day.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Coworker" },
    seo: { description: "Vote on who's wrong: a coworker presenting your casually-mentioned idea as their own." },
    featured: true,
  },
  {
    id: "wrong-separate-finances",
    slug: "partner-wants-separate-finances",
    type: "whos_wrong",
    category: "dating",
    prompt: "We've been together five years and my partner still wants to keep our finances completely separate.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Partner" },
    seo: { description: "Vote on who's wrong: wanting separate finances after five years together." },
  },
  {
    id: "wrong-wedding-no-plus-one",
    slug: "wedding-invite-no-plus-one",
    type: "whos_wrong",
    category: "friends",
    prompt: "A close friend invited me to their wedding but wouldn't extend a plus-one for my partner of two years.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Friend" },
    seo: { description: "Vote on who's wrong: a wedding invite with no plus-one for a two-year partner." },
    featured: true,
  },
  {
    id: "wrong-shared-streaming-login",
    slug: "roommate-shares-streaming-with-family",
    type: "whos_wrong",
    category: "roommates",
    prompt: "I found out my roommate has been sharing my streaming login with their entire extended family.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Roommate" },
    seo: { description: "Vote on who's wrong: a roommate sharing your streaming login with their family." },
  },
  {
    id: "wrong-cosign-loan",
    slug: "sibling-wants-cosigned-loan",
    type: "whos_wrong",
    category: "family",
    prompt: "My sibling expects me to co-sign a loan for their new business idea.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Sibling" },
    seo: { description: "Vote on who's wrong: being asked to co-sign a sibling's business loan." },
  },
  {
    id: "wrong-coworker-team-credit",
    slug: "coworker-solo-credit-team-project",
    type: "whos_wrong",
    category: "work",
    prompt: "My coworker keeps taking sole credit in meetings for a project we built together as a team.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Coworker" },
    seo: { description: "Vote on who's wrong: a coworker taking solo credit for team work." },
  },
  {
    id: "wrong-loan-then-vacation",
    slug: "lent-money-then-saw-vacation-photos",
    type: "whos_wrong",
    category: "money",
    prompt: "A friend borrowed money from me for an 'emergency,' then posted vacation photos a week later.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Friend" },
    seo: { description: "Vote on who's wrong: lending emergency money then seeing vacation photos." },
    featured: true,
  },
  {
    id: "wrong-keep-dating-apps",
    slug: "keeping-dating-apps-while-exclusive",
    type: "whos_wrong",
    category: "dating",
    prompt: "We agreed to be exclusive, but I want to keep my dating apps up 'just to see what's out there.'",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Partner" },
    seo: { description: "Vote on who's wrong: keeping dating apps active after agreeing to be exclusive." },
  },
  {
    id: "wrong-canceled-plans-third-time",
    slug: "canceled-plans-third-time-this-month",
    type: "whos_wrong",
    category: "friends",
    prompt: "I canceled plans last minute for the third time this month because I was too exhausted to go out.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Friends" },
    seo: { description: "Vote on who's wrong: repeatedly canceling plans last minute due to exhaustion." },
  },
  {
    id: "wrong-cat-destroyed-furniture",
    slug: "roommates-cat-destroyed-furniture",
    type: "whos_wrong",
    category: "roommates",
    prompt: "My roommate's cat destroyed my couch and they refuse to pay anything toward replacing it.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Roommate" },
    seo: { description: "Vote on who's wrong: a roommate's cat destroying furniture with no compensation offered." },
  },
  {
    id: "wrong-parents-unannounced-visits",
    slug: "parents-show-up-unannounced",
    type: "whos_wrong",
    category: "family",
    prompt: "My parents show up at my apartment unannounced at least once a week.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Parents" },
    seo: { description: "Vote on who's wrong: parents who show up unannounced every week." },
  },
  {
    id: "wrong-work-holiday-no-kids",
    slug: "asked-to-work-holiday-no-kids",
    type: "whos_wrong",
    category: "work",
    prompt: "I was asked to work the holiday shift because I'm the only one on the team without kids.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Manager" },
    seo: { description: "Vote on who's wrong: being scheduled to work a holiday for having no kids." },
    featured: true,
  },
  {
    id: "wrong-spent-joint-savings",
    slug: "partner-spent-joint-savings-on-hobby",
    type: "whos_wrong",
    category: "money",
    prompt: "My partner spent a chunk of our joint savings on a new hobby without discussing it with me first.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Partner" },
    seo: { description: "Vote on who's wrong: spending joint savings on a hobby without discussion." },
  },
  {
    id: "wrong-ended-things-over-text",
    slug: "ended-things-over-text-after-three-dates",
    type: "whos_wrong",
    category: "dating",
    prompt: "I ended things over text after three dates instead of doing it in person or over a call.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Date" },
    seo: { description: "Vote on who's wrong: ending things over text after three dates." },
  },
  {
    id: "wrong-told-mutual-friend-secret",
    slug: "told-mutual-friend-a-secret",
    type: "whos_wrong",
    category: "friends",
    prompt: "I told a mutual friend a secret my best friend had told me in confidence.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Best friend" },
    seo: { description: "Vote on who's wrong: sharing a friend's secret with a mutual friend." },
  },
  {
    id: "wrong-skip-family-holidays",
    slug: "skip-family-holidays-called-selfish",
    type: "whos_wrong",
    category: "family",
    prompt: "I skip every family holiday because of the drama, and my parents call me selfish for it.",
    optionA: { key: "a", label: "Me" },
    optionB: { key: "b", label: "Parents" },
    seo: { description: "Vote on who's wrong: skipping family holidays over drama and being called selfish." },
  },
];
