import type { SocialContentItem } from "@/lib/content/types";

export const HYPE: SocialContentItem[] = [
  {
    id: "hype-expensive-skincare",
    slug: "expensive-skincare",
    type: "hype",
    category: "beauty",
    prompt: "$80+ skincare serums.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether expensive skincare serums are worth the hype." },
    featured: true,
  },
  {
    id: "hype-smart-rings",
    slug: "smart-rings",
    type: "hype",
    category: "tech",
    prompt: "Smart rings that track your sleep and recovery.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether smart rings are worth the hype." },
    featured: true,
  },
  {
    id: "hype-matcha",
    slug: "matcha",
    type: "hype",
    category: "food",
    prompt: "Matcha — the drink, the flavor, the whole aesthetic.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether matcha lives up to the hype." },
  },
  {
    id: "hype-ai-subscriptions",
    slug: "ai-subscriptions",
    type: "hype",
    category: "tech",
    prompt: "$20/month AI subscriptions.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether $20/month AI subscriptions are worth the hype." },
    featured: true,
  },
  {
    id: "hype-viral-restaurants",
    slug: "viral-restaurants-long-wait",
    type: "hype",
    category: "food",
    prompt: "Viral restaurants with a two-hour wait.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether viral restaurants with long waits are worth the hype." },
  },
  {
    id: "hype-designer-sneakers",
    slug: "designer-sneakers",
    type: "hype",
    category: "fashion",
    prompt: "Designer sneakers.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether designer sneakers are worth the hype." },
  },
  {
    id: "hype-thousand-dollar-phones",
    slug: "thousand-dollar-phones",
    type: "hype",
    category: "tech",
    prompt: "$1,000+ phones.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether phones over $1,000 are worth the hype." },
    featured: true,
  },
  {
    id: "hype-standing-desks",
    slug: "standing-desks",
    type: "hype",
    category: "lifestyle",
    prompt: "Standing desks.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether standing desks are worth the hype." },
  },
  {
    id: "hype-cold-plunge",
    slug: "cold-plunge-tubs",
    type: "hype",
    category: "lifestyle",
    prompt: "Cold plunge tubs.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether cold plunge tubs are worth the hype." },
  },
  {
    id: "hype-tiktok-made-me-buy-it",
    slug: "tiktok-made-me-buy-it-gadgets",
    type: "hype",
    category: "tech",
    prompt: "\"TikTok made me buy it\" gadgets.",
    optionA: { key: "worth_it", label: "Worth it" },
    optionB: { key: "overrated", label: "Overrated" },
    seo: { description: "Vote on whether viral 'TikTok made me buy it' gadgets are worth the hype." },
  },
];
